# cart-api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-server
spec:
  selector:
    matchLabels:
      app: cart
  replicas: {{ .Values.app.cart.replicaCount }}
  template: 
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-api-container
        image: {{ .Values.image.repository }}/cart-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        envFrom: 
        - configMapRef:
            name: service-url
        - configMapRef:
            name: app-db-setting
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name:  cart-api-service
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cart-api-server-hpa
  namespace: default
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_workload="cart-api-server",
                destination_workload_namespace="default",
                reporter="destination"
              }[1m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="default",
          pod=~"cart-api-server.*"
          }
        ) by (pod)
      )
spec:
  maxReplicas: {{ .Values.hpa.cart.maxReplicas }}
  minReplicas: {{ .Values.hpa.cart.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-api-server
  metrics:
    - type: Object
      object:
        metricName: istio-requests-total
        target:
          apiVersion: v1
          kind: Pod
          name: cart-api-server
        targetValue: {{ .Values.hpa.cart.targetValue }}
