
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: loadtester
  name: loadtester
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadtester
    spec:
      containers:
      - image: tmdwn0704/loadtester:13
        name: loadtester
        resources: {}
status: {}

