# order-api-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-server
spec:
  selector:
    matchLabels:
      app: order
  replicas: {{ .Values.app.order.replicaCount }}
  template: 
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-api-container
        image: {{ .Values.image.repository }}/order-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        envFrom: 
        - configMapRef:
            name: service-url
        - configMapRef:
            name: app-db-setting
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 80
          periodSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 80
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name:  order-api-service
spec:
  selector:
    app: order
  ports:
    - name: http
      port: 8080
      targetPort: 8000
  type: ClusterIP

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: order-api-server-hpa
  namespace: default
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_workload="order-api-server",
                destination_workload_namespace="default",
                reporter="destination"
              }[1m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="default",
          pod=~"order-api-server.*"
          }
        ) by (pod)
      )
spec:
  maxReplicas: {{ .Values.hpa.order.maxReplicas }}
  minReplicas: {{ .Values.hpa.order.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-api-server
  metrics:
    - type: Object
      object:
        metricName: istio-requests-total
        target:
          apiVersion: v1
          kind: Pod
          name: order-api-server
        targetValue: {{ .Values.hpa.order.targetValue }}
