# risk version product-api-server circuit breaking
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-server
spec:
  selector:
    matchLabels:
      app: product
      version: risky
  replicas: {{ .Values.app.product.replicaCount }}
  template: 
    metadata:
      labels:
        app: product
        version: risky
    spec:
      containers:
      - name: product-api-container
        image: {{ .Values.image.repository }}/product-service:risky
        imagePullPolicy: ifNotPresent
        ports:
        - containerPort: 8000
        envFrom: 
        - configMapRef:
            name: service-url
        - configMapRef:
            name: app-db-setting

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 80
          periodSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 80
          periodSeconds: 10
      
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-for-the-product-service
spec:
  host: "product-api-service.default.svc.cluster.local"  
  trafficPolicy:
    outlierDetection: # Circuit Breakers HAVE TO BE SWITCHED ON
      maxEjectionPercent: 100
      consecutive5xxErrors: 2
      interval: 10s
      baseEjectionTime: 30s