image:
  repository: "tmdwn0704"
  pullPolicy: Always
  tag: "test69"

app:
  frontend:
    replicaCount: 1
  user:
    replicaCount: 2
  product:
    replicaCount: 1
  order:
    replicaCount: 1
  apiGateWay:
    replicaCount: 1

database:
  user:
    replicaCount: 1
  product:
    replicaCount: 1
  order:
    replicaCount: 1


