apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    argocd.argoproj.io/instance: check-face
    created-by: kubeless
    function: checkface
  name: checkface
  namespace: default
  ownerReferences:
  - apiVersion: kubeless.io/v1beta1
    kind: Function
    name: checkface
    uid: 31da657d-48b7-4872-a18a-03e5978ca2f3
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: checkface
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
