image:
  repository: "tmdwn0704"
  pullPolicy: Always
  tag: "test101"

app:
  frontend:
    replicaCount: 1
  user:
    replicaCount: 2
  product:
    replicaCount: 1
  order:
    replicaCount: 1
  apiGateWay:
    replicaCount: 1
  cart:
    replicaCount: 1
  rating:
    replicaCount: 1
  post:
    replicaCount: 1
  auction:
    replicaCount: 1

database:
  user:
    replicaCount: 1
  product:
    replicaCount: 1
  order:
    replicaCount: 1
  cart:
    replicaCount: 1
  rating:
    replicaCount: 1
  post:
    replicaCount: 1
  auction:
    replicaCount: 1

hpa:
  apiGateway:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  frontend:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  user:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  product:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  order:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  cart:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  rating:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  post:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5
  auction:
    maxReplicas: 3
    minReplicas: 1
    targetValue: 5

loadtester:
  replicas: 1



nfs: 10.0.2.116
