apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front-app
  name: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-app
    spec:
      containers:
      - image: tmdwn0704/front-app:03
        name: front-app
        env:
        - name: REACT_APP_BASE_URL
          value: "http://backend-service.default.svc:8080"
        envFrom:
        - secretRef:
            name: aws-bucket-secret
        ports:
        - containerPort: 3000
        resources: {}
status: {}
