apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: front-app
  name: front-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: front-app
status:

