apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-app":"metrics-server"},"name":"metrics-server","namespace":"kube-system"}}
  creationTimestamp: "2021-12-02T11:42:56Z"
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
  resourceVersion: "7573"
  uid: a8e35b9a-1f14-459d-9566-7c782a30118c
secrets:
- name: metrics-server-token-wlgcn

