apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      created-by: kubeless
      function: producer
    name: producer
    namespace: default
    ownerReferences:
    - apiVersion: kubeless.io/v1beta1
      kind: Function
      name: producer
      uid: 7f4bfa81-e979-46f6-9b3a-886bbfd0d138
  spec:
    maxReplicas: 3
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: producer
    targetCPUUtilizationPercentage: 10
  status:
    currentReplicas: 0
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
