apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeless
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: App/kafka
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
      allowEmpty: false
    syncOptions:    
    - Validate=false 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 5 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m 