apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: producer
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: App/producer
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD